spring.application.name=SecurityApp
spring.datasource.url=jdbc:postgresql://localhost:5432/securityTest
spring.datasource.username=airbnb
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security configs
#spring.security.user.name=monji
#spring.security.user.password=pass
#spring.security.user.roles[] = {ADMIN}
jwt.secretKey = ksjcnviaekwuhfxcmnvioh2938787uyihjsadfawfawsdfw23rf23rfew3wef


#OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
deploy.env = development